package br.jeanderson.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

public class DefaultViewController {

	// Event Listener on Button.onAction
	@FXML
	public void actionAcessarGitHub(ActionEvent event) {
		// TODO Autogenerated
	}
}
